language: python
python:
- "3.7"
before_install:
- pip install pytest==5.4.3
- pip install pytest-cov==2.10.0
- pip install codecov==2.1.8
install:
- python setup.py install
script:
- python setup.py test 
after_success:
- codecov
